{
 "title": "Kafka Connector Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Health check Card-syncer connector",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{job=~\"health-check-cardsyncer-connector\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Health check Moca connector",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{job=~\"health-check-moca-connector\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Health check Spring connector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{job=~\"health-check-spring-connector\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Health check Spark connector",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{job=~\"health-check-spark-connector\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  }
 ]
}