{
 "title": "Moca DR  -  Servers Linux",
 "description": "Dashboard Created by Mr.HIP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Hosts",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*ptime/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP ping",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*ping/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Context switches per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Context switches per second" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Disco" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*CPU/" },
     "itemTag": { "filter": "Application: CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interrupts per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Interrupts per second" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "Application: CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU idle time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "CPU idle time" },
     "itemTag": { "filter": "Application: CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Total memory" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total swap space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Total swap space" },
     "itemTag": { "filter": "Application: Memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": " Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Disco" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "Application: Memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memória" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "Application: Memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memória" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Free memory" },
     "itemTag": { "filter": "Application: Memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free swap space in %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memória" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Free swap space in %" },
     "itemTag": { "filter": "Application: Memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/: Space utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Processos" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/: Space utilization" },
     "itemTag": { "filter": "Application: Filesystem /" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/: Used space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Processos" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/: Used space" },
     "itemTag": { "filter": "Application: Filesystem /" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/: Total space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Sistema" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/: Total space" },
     "itemTag": { "filter": "Application: Filesystem /" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "Disco" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*Load average/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/app: Space utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Processos" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/app: Space utilization" },
     "itemTag": { "filter": "Application: Filesystem /app" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/app: Used space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Processos" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/app: Used space" },
     "itemTag": { "filter": "Application: Filesystem /app" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/app: Total space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Sistema" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/app: Total space" },
     "itemTag": { "filter": "Application: Filesystem /app" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Disco" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "/.*Application: Disk/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/boot: Space utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Processos" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/boot: Space utilization" },
     "itemTag": { "filter": "Application: Filesystem /boot" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/boot: Used space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Processos" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/boot: Used space" },
     "itemTag": { "filter": "Application: Filesystem /boot" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/: Total space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Sistema" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/boot: Total space" },
     "itemTag": { "filter": "Application: Filesystem /boot" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Network Interface",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Disco" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*Interface/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}